version: "3.2"
services:
  tlsoffloader:
    image: nginx:${NGINX_VERSION}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mb-platform
    restart: unless-stopped
    secrets:
      - source: tlsoffloaderconf
        target: /etc/nginx/nginx.conf
    volumes:
      - ./files/certificates/conf:/etc/letsencrypt
      - ./files/certificates/www:/var/www/certbot
      - ./sources/www/html:/usr/share/nginx/html

  certbot:
    image: certbot/certbot:${CERTBOT_VERSION}
    restart: unless-stopped
    volumes:
      - ./files/certificates/conf:/etc/letsencrypt
      - ./files/certificates/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  mb-platform:

secrets:
  tlsoffloaderconf:
    file: "./config/tlsoffloader/tlsoffloader-${ENV}.conf"