version: "3.8"

services:
  tlsoffloader:
    image: nginx:${NGINX_VERSION}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mb-platform
    restart: unless-stopped
    secrets:
      - source: tlsoffloaderconf
        target: /etc/nginx/nginx.conf
    volumes:
      - ./files/certificates/conf:/etc/letsencrypt
      - ./files/certificates/www:/var/www/certbot
      - ./files/www/html:/usr/share/nginx/html
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/dns-google:${CERTBOT_VERSION}
    restart: unless-stopped
    volumes:
      - ./files/certificates/conf:/etc/letsencrypt
      - ./files/certificates/www:/var/www/certbot
    secrets:
      - source: certbotcredential
        target: /cred.json
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  mnapi:
    image: mnapi:latest
    restart: unless-stopped
    ports:
      - "50000:50000"
    networks:
      - mb-platform   
    volumes:
      - ./files/mn-api/out:/public/out:rw

networks:
  mb-platform:

secrets:
  tlsoffloaderconf:
    file: "./files/config/tlsoffloader.conf"
  rootpass:
    file: "./files/config/mysql-root-pass.txt"
  certbotcredential:
    file: "./files/config/${DNS_CREDENTIALS}.json"
  postgrepass:
    file: "./files/config/postgre-pass.txt"