version: "3.8"

services:
  tlsoffloader:
    image: nginx:${NGINX_VERSION}
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mb-platform
    restart: unless-stopped
    secrets:
      - source: tlsoffloaderconf
        target: /etc/nginx/nginx.conf
    volumes:
      - ./files/certificates/conf:/etc/letsencrypt
      - ./files/certificates/www:/var/www/certbot
      - ./sources/www/html:/usr/share/nginx/html
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/dns-google:${CERTBOT_VERSION}
    restart: unless-stopped
    volumes:
      - ./files/certificates/conf:/etc/letsencrypt
      - ./files/certificates/www:/var/www/certbot
    secrets:
      - source: certbotcredential
        target: /cred.json
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  blagajnadb:
    image: mariadb:${MARIADB_VERSION}
    restart: unless-stopped
    command: ['mysqld', '--defaults-file=/etc/my.cnf', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--innodb-flush-log-at-trx-commit=0', '--max-sp-recursion-depth=1']
    ports:
      - "3306:3306"
    networks:
      - mb-platform
    volumes:
      - ./files/blagajnadb/mariadb/my.cnf:/etc/my.cnf:ro
      - ./files/blagajnadb/data:/var/lib/mysql:rw
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/rootpass
      LANG: C.UTF-8
    secrets:
      - source: rootpass
    cap_add:
      - SYS_NICE

  userdb:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgrepass
    networks:
      - mb-platform
    volumes:
      - ./files/userdb/data:/var/lib/postgresql/data:rw
      - ./sources/userdb/up:/docker-entrypoint-initdb.d
    secrets:
      - source: postgrepass
    ports:
      - "5432:5432"

  mnapi:
    image: mnapi:latest
    restart: unless-stopped
    ports:
      - "50000:50000"
    networks:
      - mb-platform   
    volumes:
      - ./files/mn-api/out:/public/out:rw

networks:
  mb-platform:

secrets:
  tlsoffloaderconf:
    file: "./files/config/tlsoffloader.conf"
  rootpass:
    file: "./files/config/mysql-root-pass.txt"
  certbotcredential:
    file: "./files/config/${DNS_CREDENTIALS}.json"
  postgrepass:
    file: "./files/config/postgre-pass.txt"