#!/bin/bash

verify-env() {
 [ -z "${1}" ] || [ ! "${1}" = "dev" ] && [ ! "${1}" = "test" ] && [ ! "${1}" = "stage" ] && [ ! "${1}" = "prod" ]
}
fn-exists() {
 declare -F "${1}" > /dev/null
}
rm-container() {
 if [ $# -ne 0 ]; then
  CONTAINER="${1}"
  if docker ps -a --format '{{.Names}}' | grep -q "${CONTAINER}"; then
   docker rm ${CONTAINER}
  fi
 fi
}
rm-image() {
 if [ $# -ne 0 ]; then 
  IMAGE="${1}"
  IMAGE_EXISTS=$(docker images -q "${IMAGE}" 2>/dev/null)
  if [ -n "${IMAGE_EXISTS}" ]; then
   docker rmi ${IMAGE}
  fi
 fi
}

unset ENV
export MSYS_NO_PATHCONV=1

[[ -f "./platform_version.sh" ]]               && source "./platform_version.sh"
[[ -f "./env.sh"      ]]                       && source "./env.sh"
[[ -z ${ENV} ]] && [ "${1}" != "prepare-env" ] && echo "${0}: missing or invalid env.sh; run: '${0} prepare-env { dev | test | stage | prod }'" && exit 1
[[ -f "./env-${ENV}.sh" ]]                     && source "./env-${ENV}.sh"

. "./platform-versions/v_$((PLATFORM_VERSION - 1)).sh"

prepare-env() {
 if verify-env "${1}"; then
  echo "usage: '${0} prepare-env { dev | test | stage | prod }"
  exit 1
 fi
 envsubst < "./env.template" > "./env-${1}.sh"
 [[ ! -f "./platform_version.sh" ]] && printf "%s\n" "#!/bin/bash" "" "export PLATFORM_VERSION=0" > "./platform_version.sh"
 printf "%s\n" "#!/bin/bash" "" "export ENV=${1}" > "./env.sh"
 echo "${0}: check file './env-${1}.sh', then run '${0} write-configs'"
}
write-configs() {
 mkdir -p "./files/blagajnadb/mariadb"
 mkdir -p "./files/blagajnadb/data"
 cp "./config/blagajnadb/my.cnf" "./files/blagajnadb/mariadb/my.cnf"
 echo "${BLAGAJNADB_ROOT_PASS}" > "./config/blagajnadb/mysql-root-pass-${ENV}.txt"
 envsubst '${APP_SERVER_NAME},${WEB_SERVER_NAME}'  < "./config/tlsoffloader/tlsoffloader.conf" > "./config/tlsoffloader/tlsoffloader-${ENV}.conf"
 envsubst '${NODE_VERSION}'                        < "./sources/mb-app.sample.Dockerfile"      > "./sources/mb-app.Dockerfile"
 envsubst '${PHP_VERSION}'                         < "./sources/php.sample.Dockerfile"         > "./sources/php.Dockerfile"
 envsubst '${DOTNETSDK_VERSION},${ASPNET_VERSION}' < "./sources/quotable.sample.Dockerfile"    > "./sources/quotable.Dockerfile"
 envsubst                                          < "./config/php/smtp.php"                   > "./config/php/smtp-${ENV}.php"
}

preserve-image() {
 if [ "${1}" = "img_certbot" ]; then
  if [ "${ENV}" = "prod" ]; then
   certbot-run
  fi
 else
  docker run -d --name ${1} ${2} //bin/sh -c "while true; do sleep 1; done"
 fi
}
preserve-images() {
 preserve-image img_nginx nginx:${NGINX_VERSION}
 preserve-image img_certbot certbot/dns-google:${CERTBOT_VERSION}
 preserve-image img_node node:${NODE_VERSION}
 preserve-image img_mbapp mbapp:${MBAPP_VERSION}
 preserve-image img_mariadb mariadb:${MARIADB_VERSION}
 preserve-image img_mailserver docker.io/mailserver/docker-mailserver:${MAILSERVER_VERSION}
 preserve-image img_php php:${PHP_VERSION}
 preserve-image img_dotnet mcr.microsoft.com/dotnet/sdk:${DOTNETSDK_VERSION}
 preserve-image img_aspnet mcr.microsoft.com/dotnet/aspnet:${ASPNET_VERSION}
}
release-images() {
 docker stop $(docker ps --format '{{.Names}}' | grep img_)
 docker rm $(docker ps -a --format '{{.Names}}' | grep img_)
}

### CONTAINER MANIPULATION ###

blagajnadb() {
 if fn-exists blagajnadb-"${1}"; then
  blagajnadb-"${1}" "${2}"
 else
  echo
  echo "usage: ${0} blagajnadb [param]"
  echo
  echo "PARAMS:"
  echo
  echo " --------------------------------------------------------------------------------------------------"
  echo "  upgrade [VER]   | runs the new upgrade scripts to upgrade the database to [VER] (max by default)"
  echo "  downgrade [VER] | runs the downgrade script to downgrade the database to [VER] (default: cur-1)"
  echo "  login           | logs into the database on the cli"
  echo " --------------------------------------------------------------------------------------------------"
  echo
 fi
}
blagajnadb-login() {
 DB_NAME=`docker ps --format "{{.Names}}" | grep blagajnadb`
 docker exec -it ${DB_NAME} mysql -u root -p"${DB_ROOT_PASS}" malablagajna
}
blagajnadb-upgrade() {
 if [[ -z "${1}" ]]; then UPGRADE=--full; else UPGRADE="--ver ${1}"; fi
 docker run --rm -v `pwd`/sources/blagajnadb:/blagajnadb:ro --network mb-platform_mb-platform $(docker build -f scripts/dbupdater.Dockerfile -q ./scripts) \
  dbupgrade /blagajnadb --demo ${UPGRADE} -h blagajnadb --port=3306 -u root -p"${BLAGAJNADB_ROOT_PASS}" malablagajna
}
blagajnadb-downgrade() {
 if [[ -z "${1}" ]]; then unset DOWNGRADE; else DOWNGRADE="--ver ${1}"; fi
 docker run --rm -v `pwd`/sources/blagajnadb:/blagajnadb:ro --network mb-platform_mb-platform $(docker build -f scripts/dbupdater.Dockerfile -q ./scripts) \
  dbdowngrade /blagajnadb ${DOWNGRADE} -h blagajnadb --port=3306 -u root -p"${BLAGAJNADB_ROOT_PASS}" malablagajna
}

mailserver() {
 if [ "${ENV}" != "prod" ]; then
  echo "${0}: can only execute mailserver in production environment"
  exit 1
 fi
 ./config/mailserver/setup.sh ${@}
}

infra() {
 if fn-exists infra-"${1}"; then
  infra-"${1}" "${2}"
 else
  echo
  echo "usage: ${0} infra [param]"
  echo
  echo "PARAMS:"
  echo
  echo " --------------------------------------------------------------------------------------------------"
  echo "  run                      | creates and runs infrastructure containers"
  echo "  logs [LINES] [CONTAINER] | shows last [LINES] lines of [CONTAINER]'s logs, or all by default"
  echo "  stop                     | stops and removes infrastructure containers"
  echo "  recreate                 | stops and removes infrastructure containers, then runs them anew"
  echo " --------------------------------------------------------------------------------------------------"
  echo
 fi
}
infra-run() {
 docker compose -p mb-platform -f docker-compose-infra.yml up -d
}
infra-logs() {
 if [[ -z "${1}" ]]; then LINES=all; else LINES="${1}"; fi
 if [[ ! -z "${2}" ]]; then CONTAINER="${2}"; fi
 docker compose -p mb-platform -f docker-compose-infra.yml logs -f -t --tail "${LINES}" ${CONTAINER}
}
infra-stop() {
 docker compose -p mb-platform -f docker-compose-infra.yml down
}
infra-recreate() {
 infra-stop
 infra-run
}

app() {
 if fn-exists app-"${1}"; then
  app-"${1}" "${2}"
 else
  echo
  echo "usage: ${0} app [param]"
  echo
  echo "PARAMS:"
  echo
  echo " --------------------------------------------------------------------------------------------------"
  echo "  build           | builds the mbapp web app"
  echo "  run             | creates and runs the mbapp container"
  echo "  logs [LINES]    | shows last [LINES] lines of container's logs, or all by default"
  echo "  stop            | stops and removes the container"
  echo "  rm              | removes the app container"
  echo "  rmi             | removes the app image"
  echo "  recreate        | stops and removes the container, then runs it anew"
  echo " --------------------------------------------------------------------------------------------------"
  echo
 fi
}
app-build() {
 cd sources/
 docker build -f mb-app.Dockerfile -t mbapp:latest --build-arg ENV=${ENV} .
 cd ..
}
app-run() {
 docker compose -p mb-platform -f docker-compose-apps.yml up -d --no-recreate mbapp
}
app-logs() {
 if [[ -z "${1}" ]]; then LINES=all; else LINES="${1}"; fi
 docker compose -p mb-platform -f docker-compose-apps.yml logs -f -t --tail "${LINES}" mbapp
}
app-stop() {
 docker compose -p mb-platform -f docker-compose-apps.yml stop mbapp
 docker compose -p mb-platform -f docker-compose-apps.yml rm -f mbapp
}
app-rm() {
 rm-container mbapp
}
app-rmi() {
 rm-image mbapp
}
app-recreate() {
 app-stop
 app-rm
 app-rmi
 app-build
 app-run
}

quotable() {
 if fn-exists quotable-"${1}"; then
  quotable-"${@}"
 else
  echo
  echo "usage: ${0} quotable [param]"
  echo
  echo "PARAMS:"
  echo
  echo " --------------------------------------------------------------------------------------------------"
  echo "  build           | builds quotable image"
  echo "  run <q> <a>     | runs quotable from image with parameters q (quote) and a (author)"
  echo "  rm              | removes the quotable container"
  echo "  rmi             | removes the quotable image"
  echo "  recreate        | removes the quotable container and image, then builds the new image"
  echo " --------------------------------------------------------------------------------------------------"
  echo
 fi
}
quotable-build() {
 cd sources/
 docker build -f quotable.Dockerfile -t quotable:latest .
 cd ..
}
quotable-run() {
 IMAGE_EXISTS=$(docker images -q quotable 2>/dev/null)
 if [ -n "${IMAGE_EXISTS}" ]; then
  QUOTE="${1}"
  AUTHOR="${2}"
  docker run --rm -v "`pwd`/files/images":"/app/out" quotable "${QUOTE}" "${AUTHOR}"
 else
  echo "Image 'quotable' does not exist. Please buld the image using: ${0} build"
 fi
}
quotable-rm() {
 rm-container quotable
}
quotable-rmi() {
 rm-image quotable
}
quotable-recreate() {
 quotable-rm
 quotable-rmi
 quotable-build
}

### PLATFORM VERSION MANIPULATION ###

upgrade-v1() {
 echo "${0}: upgrading v1 -> v2"
 quotable-recreate
 printf "%s\n" "#!/bin/bash" "" "export PLATFORM_VERSION=2" > "./platform_version.sh"
}
upgrade-v0() {
 echo "${0}: upgrading v0 -> v1"
 export DOMAINS=(${ALL_DOMAINS})
 CDIR=`pwd`

 # checkout specific module versions
 cd "${DBUPDATER_FOLDER}"
 git checkout "${DBUPDATER_COMMIT}"
 cd "${CDIR}"
 cd "${MBAPP_FOLDER}"
 git checkout "${MBAPP_COMMIT}"
 cd "${CDIR}"
 cd "${WWW_FOLDER}"
 git checkout "${WWW_COMMIT}"
 cd "${CDIR}"
 cd "${BLAGAJNADB_FOLDER}"
 git checkout "${BLAGAJNADB_COMMIT}"
 cd "${CDIR}"

 . "./scripts/letsencrypt/letsencrypt-init.sh"
 write-configs
 letsencrypt-init
 infra-run
 blagajnadb-upgrade "001"
 app-recreate

 # restore module versions
 cd "${DBUPDATER_FOLDER}"
 git checkout "${DBUPDATER_BRANCH}"
 cd "${CDIR}"
 cd "${MBAPP_FOLDER}"
 git checkout "${MBAPP_BRANCH}"
 cd "${CDIR}"
 cd "${WWW_FOLDER}"
 git checkout "${WWW_BRANCH}"
 cd "${CDIR}"
 cd "${BLAGAJNADB_FOLDER}"
 git checkout "${BLAGAJNADB_BRANCH}"
 cd "${CDIR}"

 printf "%s\n" "#!/bin/bash" "" "export PLATFORM_VERSION=1" > "./platform_version.sh"
}

downgrade-v2() {
 echo "${0}: downgrading v2 -> v1"
 quotable-rm
 quotable-rmi
 printf "%s\n" "#!/bin/bash" "" "export PLATFORM_VERSION=1" > "./platform_version.sh"
}
downgrade-v1() {
 echo "${0}: downgrading v1 -> v0"
 infra-stop
 app-stop
 VOL_PARAM=
 if [ "${1}" = "--vol" ]; then
  VOL_PARAM="--volumes"
 fi
 preserve-images
 set -x
 docker system prune -a ${VOL_PARAM} -f
 set +x
 release-images
 if [ "${1}" = "--vol" ]; then
  rm -rf ./files
 fi
 printf "%s\n" "#!/bin/bash" "" "export PLATFORM_VERSION=0" > "./platform_version.sh"
}

### PLATFORM MANIPULATION ###

upgrade() {
 if [ -z "${PLATFORM_VERSION}" ]; then
  PLATFORM_VERSION=0
 fi
 if fn-exists upgrade-v"${PLATFORM_VERSION}"; then
  . "./platform-versions/v_${PLATFORM_VERSION}.sh"
  upgrade-v"${PLATFORM_VERSION}"
 else
  echo "${0}: version ${PLATFORM_VERSION} cannot be upgraded: missing upgrade script"
  exit 1
 fi
}
downgrade() {
 if [ -z "${PLATFORM_VERSION}" ]; then
  PLATFORM_VERSION=0
 fi
 if fn-exists downgrade-v"${PLATFORM_VERSION}"; then
  . "./platform-versions/v_$((PLATFORM_VERSION - 1)).sh"
  downgrade-v"${PLATFORM_VERSION}" "${1}"
 else
  echo "${0}: version ${PLATFORM_VERSION} cannot be downgraded"
  exit 1
 fi
}
reupgrade() {
 if [ "${ENV}" = "prod" ]; then
  echo "${0}: refusing to reupgrade in production environment: downgrade, then upgrade manually"
  exit 1
 fi
 downgrade
 upgrade
}
reset() {
 FULL=0
 VOL=0
 if [ "${1}" = "--full" ]; then
  FULL=1
 elif [ "${1}" = "--vol" ]; then
  VOL=1
 fi
 if [ "${2}" = "--full" ]; then
  FULL=1
 elif [ "${2}" = "--vol" ]; then
  VOL=1
 fi
 if [ "${ENV}" = "dev" ] || [ "${ENV}" = "test" ]; then
  if [[ "${FULL}" -eq 1 ]]; then
   rm -f ./env*.sh
  fi
  VOL_PARAM=
  if [[ "${VOL}" -eq 1 ]]; then
   VOL_PARAM="--vol"
  fi
  rm -f ./config/tlsoffloader/tlsoffloader-*.conf
  rm -rf "./files"
  source "./platform_version.sh"
  while [[ "${PLATFORM_VERSION}" -gt 0 ]]; do
   downgrade "${VOL_PARAM}"
   source "./platform_version.sh"
  done
 else
  echo "${0}: refusing to reset ${ENV} environment"
  exit 1
 fi
}

CMD=${1}
shift

case "${CMD}" in
 prepare-env)    prepare-env ${@};;
 write-configs)  write-configs;;
 upgrade)        upgrade;;
 downgrade)      downgrade ${@};;
 reupgrade)      reupgrade;;
 reset)          reset ${@};;
 app)            app ${@};;
 blagajnadb)     blagajnadb ${@};;
 mailserver)     mailserver ${@};;
 infra)          infra ${@};;
 quotable)       quotable "${@}";;
 *)
  echo
  echo "usage: ${0} {command} [parameters]"
  echo
  echo "COMMANDS:"
  echo
  echo " ---------------------------------------------------------------------------------------------"
  echo "  prepare-env [param]    | prepares [param] environment, where [param] is dev|test|stage|prod"
  echo "  write-configs          | writes configuration files based on values in env-[ENV].sh script"
  echo " ---------------------------------------------------------------------------------------------"
  echo "  upgrade                | upgrades the platform to the next version"
  echo "  downgrade [--vol]      | downgrades the platform to the previous version [removes volumes]"
  echo "  reupgrade              | best effort to downgrade platform version, then upgrade again"
  echo "  reset [--full] [--vol] | resets the environment - development or test only!"
  echo " ---------------------------------------------------------------------------------------------"
  echo "  infra [param]          | manipulates the infrastructure containers"
  echo " ---------------------------------------------------------------------------------------------"
  echo "  mailserver [param]     | used for setting up the mailserver"
  echo "  blagajnadb [param]     | used for upgrading or downgrading blagajnadb"
  echo "  app [param]            | manipulates the mbapp container"
  echo "  quotable [param]       | manipulates the quotable container"
  echo " ---------------------------------------------------------------------------------------------"
  echo
esac
